name: flake8

on:
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: List current folder
        run: ls -la
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          flake8 --append-config=setup.cfg
      - name: Analysing the code with flake8
        run: |
          flake8 $(git ls-files '*.py')